// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAxlkMZOxtGJNOCoU4WXOllpolu7qNfxQ',
    appId: '1:225176423523:android:5be44ca037552eed6fbc56',
    messagingSenderId: '225176423523',
    projectId: 'presensi-k17',
    storageBucket: 'presensi-k17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvfsIC7CFIBrV-dF5vZ88yStHn761pIAc',
    appId: '1:225176423523:ios:1175fad44152778c6fbc56',
    messagingSenderId: '225176423523',
    projectId: 'presensi-k17',
    storageBucket: 'presensi-k17.appspot.com',
    iosClientId: '225176423523-k0ghh4j2rbuofb043mp9q45vujvbstt6.apps.googleusercontent.com',
    iosBundleId: 'com.msaiflanwr.presensi',
  );
}
